/**
 * 
 */
package com.brenner.portfoliomgmt.quotes;

import com.brenner.portfoliomgmt.quotes.retrievalservice.YahooFinanceQuoteDeserializer;
import com.fasterxml.jackson.core.Version;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.module.SimpleModule;

/**
 *
 * @author dbrenner
 * 
 */
public class YahooFinanceQuoteDeserializerTest {

	/**
	 * 
	 * @param args 
	 */
	public static void main(String[] args) throws Exception {
		
		
		String quoteString = "[\n"
				+ "	{\n"
				+ "		\"ask\": 140.07,\n"
				+ "		\"askSize\": 11,\n"
				+ "		\"averageDailyVolume10Day\": 5473280,\n"
				+ "		\"averageDailyVolume3Month\": 5110982,\n"
				+ "		\"beta\": 1.004083,\n"
				+ "		\"bid\": 140.12,\n"
				+ "		\"bidSize\": 8,\n"
				+ "		\"bookValue\": 21.18,\n"
				+ "		\"components\": [\n"
				+ "			\"^NQDMXJPLMAUD\",\n"
				+ "			\"^NQUSBLM\",\n"
				+ "			\"^NQSHYL\",\n"
				+ "			\"^NQUSB9533LMAUD\",\n"
				+ "			\"^NQGMOIN\",\n"
				+ "			\"^NQNALMEURN\",\n"
				+ "			\"^NQUSB9000LMJPYN\",\n"
				+ "			\"^NQUSB9530LM\",\n"
				+ "			\"^NQUSBLMCAD\",\n"
				+ "			\"^NQUSB9000LMEURN\",\n"
				+ "			\"^NQDMXKRJPYN\",\n"
				+ "			\"^NQDMXKRLMAUDN\",\n"
				+ "			\"^NQNA9000LMGBPN\",\n"
				+ "			\"^NQDMXJPLMAUDN\",\n"
				+ "			\"^NQDMXKRLMAUD\",\n"
				+ "			\"^NQFFUSHYN\",\n"
				+ "			\"^NQUSBLMJPY\",\n"
				+ "			\"^NQUSHEIN\",\n"
				+ "			\"^NQNA9000LMEUR\",\n"
				+ "			\"^NQNA9000LMCAD\",\n"
				+ "			\"^NQGXGBLMN\",\n"
				+ "			\"^NQUS500LCVN\",\n"
				+ "			\"^NQUSB9533LMEURN\",\n"
				+ "			\"^NQDMXKRLCJPY\",\n"
				+ "			\"^NQUSB9000LMEUR\",\n"
				+ "			\"^NQDXUSLCEUR\",\n"
				+ "			\"^NQUSB9533LMGBP\",\n"
				+ "			\"^CPQ\",\n"
				+ "			\"^CPQNTR\",\n"
				+ "			\"^NQUSB9000LMCAD\",\n"
				+ "			\"^NQUSB9533LMJPYN\",\n"
				+ "			\"^NQDM9000LMJPY\",\n"
				+ "			\"^NQG9000LMCADN\",\n"
				+ "			\"^NQDMXKRAUD\",\n"
				+ "			\"^NQDMXKRLMGBPN\",\n"
				+ "			\"^NQDXUSMLTCVN\",\n"
				+ "			\"^NQGXGBLMGBPN\",\n"
				+ "			\"^NQDM9000LMEURN\",\n"
				+ "			\"^NQGXJPLMJPYN\",\n"
				+ "			\"^NQNALMCADN\",\n"
				+ "			\"^NQUSBLMEUR\",\n"
				+ "			\"^NQG9000LMGBP\",\n"
				+ "			\"^NQDM9000LMJPYN\",\n"
				+ "			\"^NQNALMJPY\",\n"
				+ "			\"^NQUSHEI\",\n"
				+ "			\"^DAA\",\n"
				+ "			\"^MSH\",\n"
				+ "			\"^NQGXGBLMJPY\",\n"
				+ "			\"^QCRD\",\n"
				+ "			\"^NQGXJPLMJPY\",\n"
				+ "			\"^NQUSB9530LMCAD\",\n"
				+ "			\"^NQUSB9530LMGBPN\",\n"
				+ "			\"^NQDMXKR\",\n"
				+ "			\"^NQDMXGBLMCADN\",\n"
				+ "			\"^NQUSB9530LMEUR\",\n"
				+ "			\"^NQUSHEIEURN\",\n"
				+ "			\"^NQUSB9000LMJPY\",\n"
				+ "			\"^NQDMXKRLCN\",\n"
				+ "			\"^NQGXGBLMEURN\",\n"
				+ "			\"^NQGXJPLMCAD\",\n"
				+ "			\"^NQUSB9530LMN\",\n"
				+ "			\"^NQGXJPLMEUR\",\n"
				+ "			\"^NQUSB9530LMGBP\",\n"
				+ "			\"^NQDMXJPLMGBPN\",\n"
				+ "			\"^NQUSLV\",\n"
				+ "			\"^NQDMXJPLMN\",\n"
				+ "			\"^NQGIHEIGBP\",\n"
				+ "			\"^NQDM9000LMAUD\",\n"
				+ "			\"^NQDMXKRLCJPYN\",\n"
				+ "			\"^NQDMXKRLMCADN\",\n"
				+ "			\"^NQDMXKRLCEUR\",\n"
				+ "			\"^NQUSB9000LMN\",\n"
				+ "			\"^NQDXUSLC\",\n"
				+ "			\"^NQGXGBLMJPYN\",\n"
				+ "			\"^IBMSY\",\n"
				+ "			\"^NQG9000LMJPYN\",\n"
				+ "			\"^NQGIHEIGBPN\",\n"
				+ "			\"^NQUSBLMEURN\",\n"
				+ "			\"^NQDMXKRJPY\",\n"
				+ "			\"^NQDMXKRLCCAD\",\n"
				+ "			\"^NQDMXKRLCEURN\",\n"
				+ "			\"^NQG9000LMAUD\",\n"
				+ "			\"^NQUSHEIGBPN\",\n"
				+ "			\"^NQGXJPLMGBPN\",\n"
				+ "			\"^NQUSB9000LMCADN\",\n"
				+ "			\"^NQNALM\",\n"
				+ "			\"^NQUS500LC\",\n"
				+ "			\"^NQDMXGBLMJPY\",\n"
				+ "			\"^NQUSMLTCV\",\n"
				+ "			\"^NQNALMAUD\",\n"
				+ "			\"^NQNA9000LMN\",\n"
				+ "			\"^NQVMVUS\",\n"
				+ "			\"^NQDXUSLCN\",\n"
				+ "			\"^NQGXGBLMAUD\",\n"
				+ "			\"^NQUSB9530LMJPYN\",\n"
				+ "			\"^NQDXUSLCV\",\n"
				+ "			\"^NQUSBLMN\",\n"
				+ "			\"^NQDMXJPLMGBP\",\n"
				+ "			\"^NQDMXKRLMEUR\",\n"
				+ "			\"^NQNALMAUDN\",\n"
				+ "			\"^NQG9000LMEURN\",\n"
				+ "			\"^NQDM9000LMCADN\",\n"
				+ "			\"^NQFFUSHY\",\n"
				+ "			\"^NQDMXKRLMCAD\",\n"
				+ "			\"^NQDMXGBLM\",\n"
				+ "			\"^NQSHYLN\",\n"
				+ "			\"^NQNA9000LMGBP\",\n"
				+ "			\"^NQDMXGBLMJPYN\",\n"
				+ "			\"^NQG9000LMN\",\n"
				+ "			\"^NQDMXKRLMJPY\",\n"
				+ "			\"^NQUSBLMJPYN\",\n"
				+ "			\"^NQDM9000LMN\",\n"
				+ "			\"^NQDMXGBLMCAD\",\n"
				+ "			\"^XMI\",\n"
				+ "			\"^NQDMXGBLMEURN\",\n"
				+ "			\"^NQDMXKRGBPN\",\n"
				+ "			\"^NQDMXGBLMEUR\",\n"
				+ "			\"^NQDMXKRAUDN\",\n"
				+ "			\"^NQDMXKRLMJPYN\",\n"
				+ "			\"^NQUSBLMCADN\",\n"
				+ "			\"^NQDMXGBLMN\",\n"
				+ "			\"^NQUSB9533LMGBPN\",\n"
				+ "			\"^NQNALMGBPN\",\n"
				+ "			\"^NQGXGBLMCADN\",\n"
				+ "			\"^NQDMXKRLCCADN\",\n"
				+ "			\"^NQGXJPLMCADN\",\n"
				+ "			\"^BGDNTR\",\n"
				+ "			\"^NQUSHEIGBP\",\n"
				+ "			\"^NQGXJPLM\",\n"
				+ "			\"^NQNA9000LMAUD\",\n"
				+ "			\"^NQUSBLMGBP\",\n"
				+ "			\"^NQNALMN\",\n"
				+ "			\"^NQUSB9000LMAUD\",\n"
				+ "			\"^NQNA9000LM\",\n"
				+ "			\"^NQFFUSLV\",\n"
				+ "			\"^NQGXJPLMAUDN\",\n"
				+ "			\"^NQUSLVN\",\n"
				+ "			\"^NQGIHEIN\",\n"
				+ "			\"^NQCAPST\",\n"
				+ "			\"^NQUSB9530LMEURN\",\n"
				+ "			\"^NQ96DIVUS\",\n"
				+ "			\"^NQUSB9530LMAUD\",\n"
				+ "			\"^DJI\",\n"
				+ "			\"^NQDMXKRLCGBP\",\n"
				+ "			\"^NQDMXKRLM\",\n"
				+ "			\"^NQUSB9533LMJPY\",\n"
				+ "			\"^NQDM9000LMGBP\",\n"
				+ "			\"^NQDMXKRLC\",\n"
				+ "			\"^NQNALMGBP\",\n"
				+ "			\"^NQDMXJPLMJPYN\",\n"
				+ "			\"^NQG9000LMEUR\",\n"
				+ "			\"^NQGXGBLM\",\n"
				+ "			\"^NQG9000LMCAD\",\n"
				+ "			\"^NQGMOI\",\n"
				+ "			\"^NQDMXKRN\",\n"
				+ "			\"^NQUSMLTCVN\",\n"
				+ "			\"^NQCRDN\",\n"
				+ "			\"^NQUSB9533LM\",\n"
				+ "			\"^NQDMXJPLMEURN\",\n"
				+ "			\"^NQG9000LMJPY\",\n"
				+ "			\"^NQFFUSLVN\",\n"
				+ "			\"^NQNA9000LMJPYN\",\n"
				+ "			\"^NQDMXJPLM\",\n"
				+ "			\"^NQDMXKREUR\",\n"
				+ "			\"^NQUSB9533LMAUDN\",\n"
				+ "			\"^NQGXJPLMGBP\",\n"
				+ "			\"^NQDM9000LMAUDN\",\n"
				+ "			\"^NQDMXKRLMEURN\",\n"
				+ "			\"^NQUSBLMAUD\",\n"
				+ "			\"^NQGXGBLMGBP\",\n"
				+ "			\"^NQDMXKRCAD\",\n"
				+ "			\"^NQNA9000LMEURN\",\n"
				+ "			\"^DJA\",\n"
				+ "			\"^DAAXMLPREIT\",\n"
				+ "			\"^NQDXUSMLTCV\",\n"
				+ "			\"^NQUSB9533LMCAD\",\n"
				+ "			\"^NQUSB9000LMAUDN\",\n"
				+ "			\"^NQUSB9000LMGBP\",\n"
				+ "			\"^NQDXUSLCEURN\",\n"
				+ "			\"^NQUSB9533LMEUR\",\n"
				+ "			\"^NQNA9000LMAUDN\",\n"
				+ "			\"^NQG9000LMAUDN\",\n"
				+ "			\"^NQDMXKRLCAUD\",\n"
				+ "			\"^NQDXUSMEGAN\",\n"
				+ "			\"^NQNALMCAD\",\n"
				+ "			\"^NQUSB9530LMJPY\",\n"
				+ "			\"^XCI\",\n"
				+ "			\"^NQGXJPLMEURN\",\n"
				+ "			\"^NQDM9000LM\",\n"
				+ "			\"^NQDXUSLCGBP\",\n"
				+ "			\"^NQGXJPLMN\",\n"
				+ "			\"^NQNALMEUR\",\n"
				+ "			\"^NQGXGBLMEUR\",\n"
				+ "			\"^NQDMXKRGBP\",\n"
				+ "			\"^NQDM9000LMEUR\",\n"
				+ "			\"^NQDM9000LMCAD\",\n"
				+ "			\"^NQDMXGBLMGBPN\",\n"
				+ "			\"^BGD\",\n"
				+ "			\"^NQCRD\",\n"
				+ "			\"^NQDMXKRCADN\",\n"
				+ "			\"^NQGXGBLMCAD\",\n"
				+ "			\"^NQDMXGBLMGBP\",\n"
				+ "			\"^NQDMXKRLCAUDN\",\n"
				+ "			\"^NQDM9000LMGBPN\",\n"
				+ "			\"^NQDXUSLCGBPN\",\n"
				+ "			\"^NQG9000LM\",\n"
				+ "			\"^NQUSBLMGBPN\",\n"
				+ "			\"^NQDMXKRLMN\",\n"
				+ "			\"^NQUSB9530LMCADN\",\n"
				+ "			\"^NQUSB9533LMCADN\",\n"
				+ "			\"^NQUSB9533LMN\",\n"
				+ "			\"^NQGXJPLMAUD\",\n"
				+ "			\"^NQDMXGBLMAUDN\",\n"
				+ "			\"^NQUSHEIEUR\",\n"
				+ "			\"^NQUSB9000LM\",\n"
				+ "			\"^NQDMXJPLMJPY\",\n"
				+ "			\"^NQDMXKRLCGBPN\",\n"
				+ "			\"^NQVMVUSN\",\n"
				+ "			\"^NQGIHEIEURN\",\n"
				+ "			\"^NQDMXKREURN\",\n"
				+ "			\"^NQNALMJPYN\",\n"
				+ "			\"^NQUSB9000LMGBPN\",\n"
				+ "			\"^NQG9000LMGBPN\",\n"
				+ "			\"^NQDMXJPLMCADN\",\n"
				+ "			\"^NQGIHEI\",\n"
				+ "			\"^NQGIHEIEUR\",\n"
				+ "			\"^NQDMXGBLMAUD\",\n"
				+ "			\"^NQUSB9530LMAUDN\",\n"
				+ "			\"^NQUSBLMAUDN\",\n"
				+ "			\"^NQNA9000LMJPY\",\n"
				+ "			\"^NQDMXJPLMCAD\",\n"
				+ "			\"^NQDMXJPLMEUR\",\n"
				+ "			\"^NQDXUSMEGA\",\n"
				+ "			\"^NQDMXKRLMGBP\",\n"
				+ "			\"^NQDXUSLCVN\",\n"
				+ "			\"^NQGXGBLMAUDN\",\n"
				+ "			\"^NQUS500LCN\",\n"
				+ "			\"^NQNA9000LMCADN\",\n"
				+ "			\"^AXI\",\n"
				+ "			\"^NQUS500LCV\"\n"
				+ "		],\n"
				+ "		\"currency\": \"USD\",\n"
				+ "		\"customPriceAlertConfidence\": \"HIGH\",\n"
				+ "		\"dividendDate\": 1654819200,\n"
				+ "		\"dividendRate\": 6.6,\n"
				+ "		\"dividendsPerShare\": 6.56,\n"
				+ "		\"dividendYield\": 4.77,\n"
				+ "		\"earningsTimestamp\": 1658174400,\n"
				+ "		\"earningsTimestampEnd\": 1658174400,\n"
				+ "		\"earningsTimestampStart\": 1658174400,\n"
				+ "		\"ebitda\": 12120000512,\n"
				+ "		\"epsCurrentYear\": 9.69,\n"
				+ "		\"epsForward\": 10.43,\n"
				+ "		\"epsNextQuarter\": 2.35,\n"
				+ "		\"epsTrailingTwelveMonths\": 6.089,\n"
				+ "		\"esgPopulated\": false,\n"
				+ "		\"exchange\": \"NYQ\",\n"
				+ "		\"exchangeDataDelayedBy\": 0,\n"
				+ "		\"exchangeTimezoneName\": \"America/New_York\",\n"
				+ "		\"exchangeTimezoneShortName\": \"EDT\",\n"
				+ "		\"exDividendDate\": 1652054400,\n"
				+ "		\"fiftyDayAverage\": 135.1656,\n"
				+ "		\"fiftyDayAverageChange\": 5.014389,\n"
				+ "		\"fiftyDayAverageChangePercent\": 0.037098113,\n"
				+ "		\"fiftyTwoWeekHigh\": 144.73,\n"
				+ "		\"fiftyTwoWeekHighChange\": -4.550003,\n"
				+ "		\"fiftyTwoWeekHighChangePercent\": -0.03143787,\n"
				+ "		\"fiftyTwoWeekLow\": 114.56,\n"
				+ "		\"fiftyTwoWeekLowChange\": 25.619995,\n"
				+ "		\"fiftyTwoWeekLowChangePercent\": 0.22363824,\n"
				+ "		\"fiftyTwoWeekRange\": \"114.56 - 144.73\",\n"
				+ "		\"firstTradeDateMilliseconds\": -252322200000,\n"
				+ "		\"floatShares\": 897843324,\n"
				+ "		\"forwardPE\": 13.440076,\n"
				+ "		\"fullExchangeName\": \"NYSE\",\n"
				+ "		\"gmtOffSetMilliseconds\": -14400000,\n"
				+ "		\"heldPercentInsiders\": 0.08799999999999999,\n"
				+ "		\"heldPercentInstitutions\": 56.961,\n"
				+ "		\"language\": \"en-US\",\n"
				+ "		\"longName\": \"International Business Machines Corporation\",\n"
				+ "		\"market\": \"us_market\",\n"
				+ "		\"marketCap\": 125646127104,\n"
				+ "		\"marketState\": \"REGULAR\",\n"
				+ "		\"messageBoardId\": \"finmb_112350\",\n"
				+ "		\"pageViews\": {\n"
				+ "			\"longTermTrend\": \"UP\",\n"
				+ "			\"midTermTrend\": \"UP\",\n"
				+ "			\"shortTermTrend\": \"UP\"\n"
				+ "		},\n"
				+ "		\"pegRatio\": 1.07,\n"
				+ "		\"preMarketChange\": 1.06,\n"
				+ "		\"preMarketChangePercent\": 0.765673,\n"
				+ "		\"preMarketPrice\": 139.5,\n"
				+ "		\"preMarketTime\": 1656077385,\n"
				+ "		\"priceEpsCurrentYear\": 14.46646,\n"
				+ "		\"priceEpsNextQuarter\": 59.651062,\n"
				+ "		\"priceHint\": 2,\n"
				+ "		\"priceToBook\": 6.6185074,\n"
				+ "		\"priceToSales\": 2.1529126,\n"
				+ "		\"quoteSourceName\": \"Nasdaq Real Time Price\",\n"
				+ "		\"quoteSummary\": {\n"
				+ "			\"earnings\": {\n"
				+ "				\"earningsChart\": {\n"
				+ "					\"currentQuarterEstimate\": 2.29,\n"
				+ "					\"currentQuarterEstimateDate\": \"2Q\",\n"
				+ "					\"currentQuarterEstimateYear\": 2022,\n"
				+ "					\"earningsDate\": [\n"
				+ "						1658174400\n"
				+ "					],\n"
				+ "					\"quarterly\": [\n"
				+ "						{\n"
				+ "							\"actual\": 2.33,\n"
				+ "							\"date\": \"2Q2021\",\n"
				+ "							\"estimate\": 2.29\n"
				+ "						},\n"
				+ "						{\n"
				+ "							\"actual\": 2.52,\n"
				+ "							\"date\": \"3Q2021\",\n"
				+ "							\"estimate\": 2.5\n"
				+ "						},\n"
				+ "						{\n"
				+ "							\"actual\": 3.35,\n"
				+ "							\"date\": \"4Q2021\",\n"
				+ "							\"estimate\": 3.3\n"
				+ "						},\n"
				+ "						{\n"
				+ "							\"actual\": 1.4,\n"
				+ "							\"date\": \"1Q2022\",\n"
				+ "							\"estimate\": 1.38\n"
				+ "						}\n"
				+ "					]\n"
				+ "				},\n"
				+ "				\"financialCurrency\": \"USD\",\n"
				+ "				\"financialsChart\": {\n"
				+ "					\"quarterly\": [\n"
				+ "						{\n"
				+ "							\"date\": \"2Q2021\",\n"
				+ "							\"earnings\": 1325000000,\n"
				+ "							\"revenue\": 18745000000\n"
				+ "						},\n"
				+ "						{\n"
				+ "							\"date\": \"3Q2021\",\n"
				+ "							\"earnings\": 1130000000,\n"
				+ "							\"revenue\": 17618000000\n"
				+ "						},\n"
				+ "						{\n"
				+ "							\"date\": \"4Q2021\",\n"
				+ "							\"earnings\": 2333000000,\n"
				+ "							\"revenue\": 3258000000\n"
				+ "						},\n"
				+ "						{\n"
				+ "							\"date\": \"1Q2022\",\n"
				+ "							\"earnings\": 733000000,\n"
				+ "							\"revenue\": 14197000000\n"
				+ "						}\n"
				+ "					],\n"
				+ "					\"yearly\": [\n"
				+ "						{\n"
				+ "							\"date\": 2018,\n"
				+ "							\"earnings\": 8728000000,\n"
				+ "							\"revenue\": 79591000000\n"
				+ "						},\n"
				+ "						{\n"
				+ "							\"date\": 2019,\n"
				+ "							\"earnings\": 9431000000,\n"
				+ "							\"revenue\": 57714000000\n"
				+ "						},\n"
				+ "						{\n"
				+ "							\"date\": 2020,\n"
				+ "							\"earnings\": 5590000000,\n"
				+ "							\"revenue\": 55179000000\n"
				+ "						},\n"
				+ "						{\n"
				+ "							\"date\": 2021,\n"
				+ "							\"earnings\": 5743000000,\n"
				+ "							\"revenue\": 57351000000\n"
				+ "						}\n"
				+ "					]\n"
				+ "				},\n"
				+ "				\"maxAge\": 86400\n"
				+ "			}\n"
				+ "		},\n"
				+ "		\"quoteType\": \"EQUITY\",\n"
				+ "		\"region\": \"US\",\n"
				+ "		\"regularMarketChange\": 1.7399902,\n"
				+ "		\"regularMarketChangePercent\": 1.2568551,\n"
				+ "		\"regularMarketDayHigh\": 140.662,\n"
				+ "		\"regularMarketDayLow\": 139.24,\n"
				+ "		\"regularMarketDayRange\": \"139.24 - 140.662\",\n"
				+ "		\"regularMarketOpen\": 139.2,\n"
				+ "		\"regularMarketPreviousClose\": 138.44,\n"
				+ "		\"regularMarketPrice\": 140.18,\n"
				+ "		\"regularMarketTime\": 1656079116,\n"
				+ "		\"regularMarketVolume\": 477842,\n"
				+ "		\"revenue\": 58361000000.0,\n"
				+ "		\"sharesOutstanding\": 896320000,\n"
				+ "		\"sharesShort\": 19584317,\n"
				+ "		\"sharesShortPrevMonth\": 21646384,\n"
				+ "		\"shortName\": \"International Business Machines\",\n"
				+ "		\"shortPercentFloat\": 2.18,\n"
				+ "		\"shortRatio\": 3.63,\n"
				+ "		\"sourceInterval\": 15,\n"
				+ "		\"symbol\": \"IBM\",\n"
				+ "		\"targetPriceHigh\": 166.0,\n"
				+ "		\"targetPriceLow\": 115.0,\n"
				+ "		\"targetPriceMean\": 143.63,\n"
				+ "		\"targetPriceMedian\": 140.0,\n"
				+ "		\"totalCash\": 10483999700.0,\n"
				+ "		\"tradeable\": false,\n"
				+ "		\"trailingAnnualDividendRate\": 6.57,\n"
				+ "		\"trailingAnnualDividendYield\": 0.047457382,\n"
				+ "		\"trailingPE\": 23.021841,\n"
				+ "		\"triggerable\": true,\n"
				+ "		\"twoHundredDayAverage\": 129.98416,\n"
				+ "		\"twoHundredDayAverageChange\": 10.195831,\n"
				+ "		\"twoHundredDayAverageChangePercent\": 0.07843903000000001,\n"
				+ "		\"typeDisp\": \"Equity\"\n"
				+ "	}\n"
				+ "]";
		
		SimpleModule module = new SimpleModule("QuoteDeserializer", new Version(1, 0, 0, null, null, null));
		module.addDeserializer(Quote.class, new YahooFinanceQuoteDeserializer());
		ObjectMapper mapper = new ObjectMapper();
		mapper.registerModule(module);
		
		Quote quote = mapper.readValue(quoteString, Quote.class);

	}

}
